### ISSUE TITLE
curl: (7) Failed to connect to 127.0.0.1 port 6969 after 0 ms: Couldn't connect to server

### ISSUE THREAD

**Issue by verbes4** [SideStore/SideServer-for-Linux#10]
```
➜  SideServer-for-Linux (main) python3 main.py
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (7) Failed to connect to 127.0.0.1 port 6969 after 0 ms: Couldn't connect to server
libplist is not available on this machine. 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (7) Failed to connect to 127.0.0.1 port 6969 after 0 ms: Couldn't connect to server
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (7) Failed to connect to 127.0.0.1 port 6969 after 0 ms: Couldn't connect to server
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (7) Failed to connect to 127.0.0.1 port 6969 after 0 ms: Couldn't connect to server
^CTraceback (most recent call last):
  File "/home/mmm/Documents/SideServer-for-Linux/main.py", line 1066, in <module>
    main()
  File "/home/mmm/Documents/SideServer-for-Linux/main.py", line 137, in main
    Gtk.main()
  File "/usr/lib/python3.11/site-packages/gi/overrides/Gtk.py", line 1692, in main
    with register_sigint_fallback(Gtk.main_quit):
  File "/usr/lib/python3.11/contextlib.py", line 144, in __exit__
    next(self.gen)
  File "/usr/lib/python3.11/site-packages/gi/_ossighelper.py", line 237, in register_sigint_fallback
    signal.default_int_handler(signal.SIGINT, None)
KeyboardInterrupt
^CException ignored in: <module 'threading' from '/usr/lib/python3.11/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1590, in _shutdown
    lock.acquire()
KeyboardInterrupt: 
```
On first run, downloaded the apk perfectly fine but refused to connect to server. Subsequent runs have the same error.
Running on Arch Linux, all dependencies have been installed.

**Comment by PR1MEC0DE** [comment]
I have the same problem.

**Comment by eli-sauvage** [comment]
Hi!
A simple way is to run the anisette server in docker !
`docker run -d -p 6969:6969 --name anisette dadoum/anisette-server:latest`
found here : https://github.com/Dadoum/Provision#docker-container

edit : Then `ALTSERVER_ANISETTE_SERVER=http://127.0.0.1:6969 python main.py` so the program will simply connect to it and not  try to create the local server. Not sure why it needs the environment variable though, but on my computer the python script can't connect without it.
